server:
  port: 6000

spring:
  application:
    name: auth
  profiles:
    active: native
  data:
    mongodb:
      database: test
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka