server:
  port: 6000

spring:
  application:
    name: auth
  profiles:
    active: native
  data:
    mongodb:
      database: test      
            
security:
  oauth2:
    resource:
      filter-order: 3
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka