server:
  port: 8080

spring:
  application:
    name: zuul
  profiles:
    active: native

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
      
zuul:
  host:
    socket-timeout-millis: 3000
  routes:
    notas:
      serviceId: notas
    tablo:
      serviceId: tablon