server:
  port: 8080

spring:
  application:
    name: zuul
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000
      
zuul:
  routes:
    notas:
      serviceId: notas
    tablo:
      serviceId: tablon