server:
  port: 8082

spring:
  application:
    name: tablon
  profiles:
    active: native

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
