server:
  port: 8081

spring:
  application:
    name: notas
  profiles:
    active: native
  data:
    mongodb:
      database: test

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka