server:
  port: 8081

spring:
  application:
    name: rest
  profiles:
    active: native
  data:
    mongodb:
      database: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka